---
- name: Restart RabbitMQ Service
  ansible.builtin.systemd_service:
    name: "{{ rabbitmq_conatiner_name }}"
    state: restarted
    enabled: "{{ rabbitmq_service_enabled }}"
    daemon_reload: true
  when: not ansible_check_mode
